# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3825afbe1b5e4420b0320481a01e9d92321d85907a32b9ea029fd34046d89b4793970fd40dadbc1eaa830eab4c052c8c9122cee0945d60ba6e8eb44f3963707a

test:
  secret_key_base: c5faeacd2b6a6b4b69dbc8442be8e14d08de03bcb3cd4722cfcebb3bfaef56f2893d0d36a65922f3418b38b6bdf50c37681783030c12394a99165f91adc48952

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
